/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Assignment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'caregiverId' : IDL.Opt(IDL.Nat),
  'patientId' : IDL.Nat,
  'createdAt' : Time,
  'nurseId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Alert = IDL.Record({
  'id' : IDL.Nat,
  'resolved' : IDL.Bool,
  'alertType' : IDL.Text,
  'patientId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'timestamp' : Time,
  'severity' : IDL.Text,
  'resolvedBy' : IDL.Opt(IDL.Nat),
});
export const Caregiver = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'hospitalId' : IDL.Nat,
  'assignedPatientIds' : IDL.Vec(IDL.Nat),
});
export const EmergencyLog = IDL.Record({
  'id' : IDL.Nat,
  'patientId' : IDL.Nat,
  'triggeredBy' : IDL.Nat,
  'timestamp' : Time,
  'notifiedUsers' : IDL.Vec(IDL.Nat),
});
export const Hospital = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'adminId' : IDL.Nat,
});
export const Nurse = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'hospitalId' : IDL.Nat,
  'assignedPatientIds' : IDL.Vec(IDL.Nat),
});
export const Patient = IDL.Record({
  'id' : IDL.Nat,
  'age' : IDL.Nat,
  'caregiverId' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'lastGestureAlert' : IDL.Opt(Time),
  'photoUrl' : IDL.Opt(IDL.Text),
  'familyMemberIds' : IDL.Vec(IDL.Nat),
  'bedNumber' : IDL.Text,
  'emergencyContacts' : IDL.Vec(IDL.Text),
  'isActive' : IDL.Bool,
  'uniqueCode' : IDL.Text,
  'salineLevel' : IDL.Nat,
  'hospitalId' : IDL.Nat,
  'postureStatus' : IDL.Text,
  'medicalHistory' : IDL.Text,
  'nurseId' : IDL.Opt(IDL.Nat),
  'bloodGroup' : IDL.Text,
});
export const Role = IDL.Variant({
  'patient' : IDL.Null,
  'admin' : IDL.Null,
  'familyMember' : IDL.Null,
  'nurse' : IDL.Null,
  'caregiver' : IDL.Null,
});
export const User = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'hospitalId' : IDL.Opt(IDL.Nat),
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});
export const UserProfile = IDL.Record({
  'userId' : IDL.Nat,
  'name' : IDL.Text,
  'role' : Role,
  'email' : IDL.Text,
  'hospitalId' : IDL.Opt(IDL.Nat),
  'profilePhotoUrl' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptAssignment' : IDL.Func([IDL.Nat], [Assignment], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlert' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Alert], []),
  'createAssignment' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
      [Assignment],
      [],
    ),
  'createCaregiver' : IDL.Func([IDL.Text, IDL.Nat], [Caregiver], []),
  'createEmergencyLog' : IDL.Func(
      [IDL.Nat, IDL.Vec(IDL.Nat)],
      [EmergencyLog],
      [],
    ),
  'createHospital' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Hospital], []),
  'createNurse' : IDL.Func([IDL.Text, IDL.Nat], [Nurse], []),
  'createPatient' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [Patient],
      [],
    ),
  'createUser' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Role,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [User],
      [],
    ),
  'getAlert' : IDL.Func([IDL.Nat], [Alert], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCaregiver' : IDL.Func([IDL.Nat], [Caregiver], ['query']),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalPatients' : IDL.Nat,
          'alertsToday' : IDL.Nat,
          'totalNurses' : IDL.Nat,
          'totalHospitals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getHospital' : IDL.Func([IDL.Nat], [Hospital], ['query']),
  'getNurse' : IDL.Func([IDL.Nat], [Nurse], ['query']),
  'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
  'getPatientByUniqueCode' : IDL.Func([IDL.Text], [Patient], ['query']),
  'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'listAlertsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
  'listAssignmentsByNurse' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'listAssignmentsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Assignment)],
      ['query'],
    ),
  'listEmergencyLogsByPatient' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(EmergencyLog)],
      ['query'],
    ),
  'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
  'listUnresolvedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
  'listUsersByHospital' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
  'listUsersByRole' : IDL.Func([Role], [IDL.Vec(User)], ['query']),
  'rejectAssignment' : IDL.Func([IDL.Nat], [Assignment], []),
  'resolveAlert' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Alert], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchPatientsByName' : IDL.Func([IDL.Text], [IDL.Vec(Patient)], ['query']),
  'updateCaregiver' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
      [Caregiver],
      [],
    ),
  'updateGestureAlert' : IDL.Func([IDL.Nat], [Patient], []),
  'updateHospital' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
      [Hospital],
      [],
    ),
  'updateNurse' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
      [Nurse],
      [],
    ),
  'updatePatient' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Vec(IDL.Nat),
        IDL.Nat,
        IDL.Text,
        IDL.Opt(Time),
        IDL.Text,
        IDL.Vec(IDL.Text),
        IDL.Bool,
      ],
      [Patient],
      [],
    ),
  'updatePostureStatus' : IDL.Func([IDL.Nat, IDL.Text], [Patient], []),
  'updateSalineLevel' : IDL.Func([IDL.Nat, IDL.Nat], [Patient], []),
  'updateUser' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Role,
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [User],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Assignment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'caregiverId' : IDL.Opt(IDL.Nat),
    'patientId' : IDL.Nat,
    'createdAt' : Time,
    'nurseId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Alert = IDL.Record({
    'id' : IDL.Nat,
    'resolved' : IDL.Bool,
    'alertType' : IDL.Text,
    'patientId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'timestamp' : Time,
    'severity' : IDL.Text,
    'resolvedBy' : IDL.Opt(IDL.Nat),
  });
  const Caregiver = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'hospitalId' : IDL.Nat,
    'assignedPatientIds' : IDL.Vec(IDL.Nat),
  });
  const EmergencyLog = IDL.Record({
    'id' : IDL.Nat,
    'patientId' : IDL.Nat,
    'triggeredBy' : IDL.Nat,
    'timestamp' : Time,
    'notifiedUsers' : IDL.Vec(IDL.Nat),
  });
  const Hospital = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'adminId' : IDL.Nat,
  });
  const Nurse = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'hospitalId' : IDL.Nat,
    'assignedPatientIds' : IDL.Vec(IDL.Nat),
  });
  const Patient = IDL.Record({
    'id' : IDL.Nat,
    'age' : IDL.Nat,
    'caregiverId' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'lastGestureAlert' : IDL.Opt(Time),
    'photoUrl' : IDL.Opt(IDL.Text),
    'familyMemberIds' : IDL.Vec(IDL.Nat),
    'bedNumber' : IDL.Text,
    'emergencyContacts' : IDL.Vec(IDL.Text),
    'isActive' : IDL.Bool,
    'uniqueCode' : IDL.Text,
    'salineLevel' : IDL.Nat,
    'hospitalId' : IDL.Nat,
    'postureStatus' : IDL.Text,
    'medicalHistory' : IDL.Text,
    'nurseId' : IDL.Opt(IDL.Nat),
    'bloodGroup' : IDL.Text,
  });
  const Role = IDL.Variant({
    'patient' : IDL.Null,
    'admin' : IDL.Null,
    'familyMember' : IDL.Null,
    'nurse' : IDL.Null,
    'caregiver' : IDL.Null,
  });
  const User = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'hospitalId' : IDL.Opt(IDL.Nat),
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  const UserProfile = IDL.Record({
    'userId' : IDL.Nat,
    'name' : IDL.Text,
    'role' : Role,
    'email' : IDL.Text,
    'hospitalId' : IDL.Opt(IDL.Nat),
    'profilePhotoUrl' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptAssignment' : IDL.Func([IDL.Nat], [Assignment], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlert' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Alert], []),
    'createAssignment' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Opt(IDL.Nat)],
        [Assignment],
        [],
      ),
    'createCaregiver' : IDL.Func([IDL.Text, IDL.Nat], [Caregiver], []),
    'createEmergencyLog' : IDL.Func(
        [IDL.Nat, IDL.Vec(IDL.Nat)],
        [EmergencyLog],
        [],
      ),
    'createHospital' : IDL.Func([IDL.Text, IDL.Text, IDL.Nat], [Hospital], []),
    'createNurse' : IDL.Func([IDL.Text, IDL.Nat], [Nurse], []),
    'createPatient' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [Patient],
        [],
      ),
    'createUser' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Role,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [User],
        [],
      ),
    'getAlert' : IDL.Func([IDL.Nat], [Alert], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCaregiver' : IDL.Func([IDL.Nat], [Caregiver], ['query']),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalPatients' : IDL.Nat,
            'alertsToday' : IDL.Nat,
            'totalNurses' : IDL.Nat,
            'totalHospitals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getHospital' : IDL.Func([IDL.Nat], [Hospital], ['query']),
    'getNurse' : IDL.Func([IDL.Nat], [Nurse], ['query']),
    'getPatient' : IDL.Func([IDL.Nat], [Patient], ['query']),
    'getPatientByUniqueCode' : IDL.Func([IDL.Text], [Patient], ['query']),
    'getUser' : IDL.Func([IDL.Nat], [User], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'listAlertsByPatient' : IDL.Func([IDL.Nat], [IDL.Vec(Alert)], ['query']),
    'listAssignmentsByNurse' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'listAssignmentsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Assignment)],
        ['query'],
      ),
    'listEmergencyLogsByPatient' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(EmergencyLog)],
        ['query'],
      ),
    'listHospitals' : IDL.Func([], [IDL.Vec(Hospital)], ['query']),
    'listUnresolvedAlerts' : IDL.Func([], [IDL.Vec(Alert)], ['query']),
    'listUsersByHospital' : IDL.Func([IDL.Nat], [IDL.Vec(User)], ['query']),
    'listUsersByRole' : IDL.Func([Role], [IDL.Vec(User)], ['query']),
    'rejectAssignment' : IDL.Func([IDL.Nat], [Assignment], []),
    'resolveAlert' : IDL.Func([IDL.Nat, IDL.Opt(IDL.Text)], [Alert], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchPatientsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Patient)],
        ['query'],
      ),
    'updateCaregiver' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat)],
        [Caregiver],
        [],
      ),
    'updateGestureAlert' : IDL.Func([IDL.Nat], [Patient], []),
    'updateHospital' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Nat],
        [Hospital],
        [],
      ),
    'updateNurse' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Vec(IDL.Nat), IDL.Bool],
        [Nurse],
        [],
      ),
    'updatePatient' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Vec(IDL.Nat),
          IDL.Nat,
          IDL.Text,
          IDL.Opt(Time),
          IDL.Text,
          IDL.Vec(IDL.Text),
          IDL.Bool,
        ],
        [Patient],
        [],
      ),
    'updatePostureStatus' : IDL.Func([IDL.Nat, IDL.Text], [Patient], []),
    'updateSalineLevel' : IDL.Func([IDL.Nat, IDL.Nat], [Patient], []),
    'updateUser' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Role,
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [User],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };