/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Alert {
  'id' : bigint,
  'resolved' : boolean,
  'alertType' : string,
  'patientId' : bigint,
  'notes' : [] | [string],
  'timestamp' : Time,
  'severity' : string,
  'resolvedBy' : [] | [bigint],
}
export interface Assignment {
  'id' : bigint,
  'status' : string,
  'caregiverId' : [] | [bigint],
  'patientId' : bigint,
  'createdAt' : Time,
  'nurseId' : bigint,
}
export interface Caregiver {
  'id' : bigint,
  'name' : string,
  'hospitalId' : bigint,
  'assignedPatientIds' : Array<bigint>,
}
export interface EmergencyLog {
  'id' : bigint,
  'patientId' : bigint,
  'triggeredBy' : bigint,
  'timestamp' : Time,
  'notifiedUsers' : Array<bigint>,
}
export interface Hospital {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'adminId' : bigint,
}
export interface Nurse {
  'id' : bigint,
  'name' : string,
  'isAvailable' : boolean,
  'hospitalId' : bigint,
  'assignedPatientIds' : Array<bigint>,
}
export interface Patient {
  'id' : bigint,
  'age' : bigint,
  'caregiverId' : [] | [bigint],
  'name' : string,
  'lastGestureAlert' : [] | [Time],
  'photoUrl' : [] | [string],
  'familyMemberIds' : Array<bigint>,
  'bedNumber' : string,
  'emergencyContacts' : Array<string>,
  'isActive' : boolean,
  'uniqueCode' : string,
  'salineLevel' : bigint,
  'hospitalId' : bigint,
  'postureStatus' : string,
  'medicalHistory' : string,
  'nurseId' : [] | [bigint],
  'bloodGroup' : string,
}
export type Role = { 'patient' : null } |
  { 'admin' : null } |
  { 'familyMember' : null } |
  { 'nurse' : null } |
  { 'caregiver' : null };
export type Time = bigint;
export interface User {
  'id' : bigint,
  'name' : string,
  'role' : Role,
  'email' : string,
  'hospitalId' : [] | [bigint],
  'profilePhotoUrl' : [] | [string],
  'phone' : [] | [string],
}
export interface UserProfile {
  'userId' : bigint,
  'name' : string,
  'role' : Role,
  'email' : string,
  'hospitalId' : [] | [bigint],
  'profilePhotoUrl' : [] | [string],
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptAssignment' : ActorMethod<[bigint], Assignment>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAlert' : ActorMethod<[bigint, string, string], Alert>,
  'createAssignment' : ActorMethod<[bigint, bigint, [] | [bigint]], Assignment>,
  'createCaregiver' : ActorMethod<[string, bigint], Caregiver>,
  'createEmergencyLog' : ActorMethod<[bigint, Array<bigint>], EmergencyLog>,
  'createHospital' : ActorMethod<[string, string, bigint], Hospital>,
  'createNurse' : ActorMethod<[string, bigint], Nurse>,
  'createPatient' : ActorMethod<
    [
      string,
      bigint,
      [] | [string],
      string,
      string,
      string,
      bigint,
      string,
      Array<string>,
    ],
    Patient
  >,
  'createUser' : ActorMethod<
    [string, string, Role, [] | [bigint], [] | [string], [] | [string]],
    User
  >,
  'getAlert' : ActorMethod<[bigint], Alert>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCaregiver' : ActorMethod<[bigint], Caregiver>,
  'getDashboardStats' : ActorMethod<
    [],
    {
      'totalPatients' : bigint,
      'alertsToday' : bigint,
      'totalNurses' : bigint,
      'totalHospitals' : bigint,
    }
  >,
  'getHospital' : ActorMethod<[bigint], Hospital>,
  'getNurse' : ActorMethod<[bigint], Nurse>,
  'getPatient' : ActorMethod<[bigint], Patient>,
  'getPatientByUniqueCode' : ActorMethod<[string], Patient>,
  'getUser' : ActorMethod<[bigint], User>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAlerts' : ActorMethod<[], Array<Alert>>,
  'listAlertsByPatient' : ActorMethod<[bigint], Array<Alert>>,
  'listAssignmentsByNurse' : ActorMethod<[bigint], Array<Assignment>>,
  'listAssignmentsByPatient' : ActorMethod<[bigint], Array<Assignment>>,
  'listEmergencyLogsByPatient' : ActorMethod<[bigint], Array<EmergencyLog>>,
  'listHospitals' : ActorMethod<[], Array<Hospital>>,
  'listUnresolvedAlerts' : ActorMethod<[], Array<Alert>>,
  'listUsersByHospital' : ActorMethod<[bigint], Array<User>>,
  'listUsersByRole' : ActorMethod<[Role], Array<User>>,
  'rejectAssignment' : ActorMethod<[bigint], Assignment>,
  'resolveAlert' : ActorMethod<[bigint, [] | [string]], Alert>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchPatientsByName' : ActorMethod<[string], Array<Patient>>,
  'updateCaregiver' : ActorMethod<
    [bigint, string, bigint, Array<bigint>],
    Caregiver
  >,
  'updateGestureAlert' : ActorMethod<[bigint], Patient>,
  'updateHospital' : ActorMethod<[bigint, string, string, bigint], Hospital>,
  'updateNurse' : ActorMethod<
    [bigint, string, bigint, Array<bigint>, boolean],
    Nurse
  >,
  'updatePatient' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      [] | [string],
      string,
      string,
      string,
      bigint,
      [] | [bigint],
      [] | [bigint],
      Array<bigint>,
      bigint,
      string,
      [] | [Time],
      string,
      Array<string>,
      boolean,
    ],
    Patient
  >,
  'updatePostureStatus' : ActorMethod<[bigint, string], Patient>,
  'updateSalineLevel' : ActorMethod<[bigint, bigint], Patient>,
  'updateUser' : ActorMethod<
    [bigint, string, string, Role, [] | [bigint], [] | [string], [] | [string]],
    User
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];