/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    userId: bigint;
    name: string;
    role: Role;
    email: string;
    hospitalId?: bigint;
    profilePhotoUrl?: string;
    phone?: string;
}
export type Time = bigint;
export interface User {
    id: bigint;
    name: string;
    role: Role;
    email: string;
    hospitalId?: bigint;
    profilePhotoUrl?: string;
    phone?: string;
}
export interface Hospital {
    id: bigint;
    name: string;
    address: string;
    adminId: bigint;
}
export interface EmergencyLog {
    id: bigint;
    patientId: bigint;
    triggeredBy: bigint;
    timestamp: Time;
    notifiedUsers: Array<bigint>;
}
export interface Nurse {
    id: bigint;
    name: string;
    isAvailable: boolean;
    hospitalId: bigint;
    assignedPatientIds: Array<bigint>;
}
export interface Caregiver {
    id: bigint;
    name: string;
    hospitalId: bigint;
    assignedPatientIds: Array<bigint>;
}
export interface Assignment {
    id: bigint;
    status: string;
    caregiverId?: bigint;
    patientId: bigint;
    createdAt: Time;
    nurseId: bigint;
}
export interface Alert {
    id: bigint;
    resolved: boolean;
    alertType: string;
    patientId: bigint;
    notes?: string;
    timestamp: Time;
    severity: string;
    resolvedBy?: bigint;
}
export interface Patient {
    id: bigint;
    age: bigint;
    caregiverId?: bigint;
    name: string;
    lastGestureAlert?: Time;
    photoUrl?: string;
    familyMemberIds: Array<bigint>;
    bedNumber: string;
    emergencyContacts: Array<string>;
    isActive: boolean;
    uniqueCode: string;
    salineLevel: bigint;
    hospitalId: bigint;
    postureStatus: string;
    medicalHistory: string;
    nurseId?: bigint;
    bloodGroup: string;
}
export enum Role {
    patient = "patient",
    admin = "admin",
    familyMember = "familyMember",
    nurse = "nurse",
    caregiver = "caregiver"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptAssignment(id: bigint): Promise<Assignment>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createAlert(patientId: bigint, alertType: string, severity: string): Promise<Alert>;
    createAssignment(patientId: bigint, nurseId: bigint, caregiverId: bigint | null): Promise<Assignment>;
    createCaregiver(name: string, hospitalId: bigint): Promise<Caregiver>;
    createEmergencyLog(patientId: bigint, notifiedUsers: Array<bigint>): Promise<EmergencyLog>;
    createHospital(name: string, address: string, adminId: bigint): Promise<Hospital>;
    createNurse(name: string, hospitalId: bigint): Promise<Nurse>;
    createPatient(name: string, age: bigint, photoUrl: string | null, medicalHistory: string, bloodGroup: string, bedNumber: string, hospitalId: bigint, uniqueCode: string, emergencyContacts: Array<string>): Promise<Patient>;
    createUser(name: string, email: string, role: Role, hospitalId: bigint | null, profilePhotoUrl: string | null, phone: string | null): Promise<User>;
    getAlert(id: bigint): Promise<Alert>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCaregiver(id: bigint): Promise<Caregiver>;
    getDashboardStats(): Promise<{
        totalPatients: bigint;
        alertsToday: bigint;
        totalNurses: bigint;
        totalHospitals: bigint;
    }>;
    getHospital(id: bigint): Promise<Hospital>;
    getNurse(id: bigint): Promise<Nurse>;
    getPatient(id: bigint): Promise<Patient>;
    getPatientByUniqueCode(uniqueCode: string): Promise<Patient>;
    getUser(id: bigint): Promise<User>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAlerts(): Promise<Array<Alert>>;
    listAlertsByPatient(patientId: bigint): Promise<Array<Alert>>;
    listAssignmentsByNurse(nurseId: bigint): Promise<Array<Assignment>>;
    listAssignmentsByPatient(patientId: bigint): Promise<Array<Assignment>>;
    listEmergencyLogsByPatient(patientId: bigint): Promise<Array<EmergencyLog>>;
    listHospitals(): Promise<Array<Hospital>>;
    listUnresolvedAlerts(): Promise<Array<Alert>>;
    listUsersByHospital(hospitalId: bigint): Promise<Array<User>>;
    listUsersByRole(role: Role): Promise<Array<User>>;
    rejectAssignment(id: bigint): Promise<Assignment>;
    resolveAlert(id: bigint, notes: string | null): Promise<Alert>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchPatientsByName(name: string): Promise<Array<Patient>>;
    updateCaregiver(id: bigint, name: string, hospitalId: bigint, assignedPatientIds: Array<bigint>): Promise<Caregiver>;
    updateGestureAlert(patientId: bigint): Promise<Patient>;
    updateHospital(id: bigint, name: string, address: string, adminId: bigint): Promise<Hospital>;
    updateNurse(id: bigint, name: string, hospitalId: bigint, assignedPatientIds: Array<bigint>, isAvailable: boolean): Promise<Nurse>;
    updatePatient(id: bigint, name: string, age: bigint, photoUrl: string | null, medicalHistory: string, bloodGroup: string, bedNumber: string, hospitalId: bigint, nurseId: bigint | null, caregiverId: bigint | null, familyMemberIds: Array<bigint>, salineLevel: bigint, postureStatus: string, lastGestureAlert: Time | null, uniqueCode: string, emergencyContacts: Array<string>, isActive: boolean): Promise<Patient>;
    updatePostureStatus(patientId: bigint, status: string): Promise<Patient>;
    updateSalineLevel(patientId: bigint, level: bigint): Promise<Patient>;
    updateUser(id: bigint, name: string, email: string, role: Role, hospitalId: bigint | null, profilePhotoUrl: string | null, phone: string | null): Promise<User>;
}
import type { Alert as _Alert, Assignment as _Assignment, Patient as _Patient, Role as _Role, Time as _Time, User as _User, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptAssignment(arg0: bigint): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptAssignment(arg0);
                return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptAssignment(arg0);
            return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n4(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createAlert(arg0: bigint, arg1: string, arg2: string): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.createAlert(arg0, arg1, arg2);
                return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAlert(arg0, arg1, arg2);
            return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async createAssignment(arg0: bigint, arg1: bigint, arg2: bigint | null): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.createAssignment(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
                return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAssignment(arg0, arg1, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg2));
            return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createCaregiver(arg0: string, arg1: bigint): Promise<Caregiver> {
        if (this.processError) {
            try {
                const result = await this.actor.createCaregiver(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCaregiver(arg0, arg1);
            return result;
        }
    }
    async createEmergencyLog(arg0: bigint, arg1: Array<bigint>): Promise<EmergencyLog> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmergencyLog(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmergencyLog(arg0, arg1);
            return result;
        }
    }
    async createHospital(arg0: string, arg1: string, arg2: bigint): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.createHospital(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createHospital(arg0, arg1, arg2);
            return result;
        }
    }
    async createNurse(arg0: string, arg1: bigint): Promise<Nurse> {
        if (this.processError) {
            try {
                const result = await this.actor.createNurse(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNurse(arg0, arg1);
            return result;
        }
    }
    async createPatient(arg0: string, arg1: bigint, arg2: string | null, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: string, arg8: Array<string>): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatient(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatient(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createUser(arg0: string, arg1: string, arg2: Role, arg3: bigint | null, arg4: string | null, arg5: string | null): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
                return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUser(arg0, arg1, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5));
            return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAlert(arg0: bigint): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.getAlert(arg0);
                return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAlert(arg0);
            return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCaregiver(arg0: bigint): Promise<Caregiver> {
        if (this.processError) {
            try {
                const result = await this.actor.getCaregiver(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCaregiver(arg0);
            return result;
        }
    }
    async getDashboardStats(): Promise<{
        totalPatients: bigint;
        alertsToday: bigint;
        totalNurses: bigint;
        totalHospitals: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getHospital(arg0: bigint): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.getHospital(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHospital(arg0);
            return result;
        }
    }
    async getNurse(arg0: bigint): Promise<Nurse> {
        if (this.processError) {
            try {
                const result = await this.actor.getNurse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNurse(arg0);
            return result;
        }
    }
    async getPatient(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatient(arg0);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatient(arg0);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientByUniqueCode(arg0: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientByUniqueCode(arg0);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientByUniqueCode(arg0);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUser(arg0: bigint): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.getUser(arg0);
                return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUser(arg0);
            return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlerts();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlerts();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAlertsByPatient(arg0: bigint): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAlertsByPatient(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAlertsByPatient(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignmentsByNurse(arg0: bigint): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignmentsByNurse(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignmentsByNurse(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listAssignmentsByPatient(arg0: bigint): Promise<Array<Assignment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAssignmentsByPatient(arg0);
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAssignmentsByPatient(arg0);
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async listEmergencyLogsByPatient(arg0: bigint): Promise<Array<EmergencyLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.listEmergencyLogsByPatient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listEmergencyLogsByPatient(arg0);
            return result;
        }
    }
    async listHospitals(): Promise<Array<Hospital>> {
        if (this.processError) {
            try {
                const result = await this.actor.listHospitals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listHospitals();
            return result;
        }
    }
    async listUnresolvedAlerts(): Promise<Array<Alert>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUnresolvedAlerts();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUnresolvedAlerts();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByHospital(arg0: bigint): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByHospital(arg0);
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByHospital(arg0);
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async listUsersByRole(arg0: Role): Promise<Array<User>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsersByRole(to_candid_Role_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsersByRole(to_candid_Role_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async rejectAssignment(arg0: bigint): Promise<Assignment> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectAssignment(arg0);
                return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectAssignment(arg0);
            return from_candid_Assignment_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async resolveAlert(arg0: bigint, arg1: string | null): Promise<Alert> {
        if (this.processError) {
            try {
                const result = await this.actor.resolveAlert(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resolveAlert(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Alert_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n28(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchPatientsByName(arg0: string): Promise<Array<Patient>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchPatientsByName(arg0);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchPatientsByName(arg0);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCaregiver(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<bigint>): Promise<Caregiver> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCaregiver(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCaregiver(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateGestureAlert(arg0: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGestureAlert(arg0);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGestureAlert(arg0);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateHospital(arg0: bigint, arg1: string, arg2: string, arg3: bigint): Promise<Hospital> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHospital(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHospital(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateNurse(arg0: bigint, arg1: string, arg2: bigint, arg3: Array<bigint>, arg4: boolean): Promise<Nurse> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNurse(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNurse(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async updatePatient(arg0: bigint, arg1: string, arg2: bigint, arg3: string | null, arg4: string, arg5: string, arg6: string, arg7: bigint, arg8: bigint | null, arg9: bigint | null, arg10: Array<bigint>, arg11: bigint, arg12: string, arg13: Time | null, arg14: string, arg15: Array<string>, arg16: boolean): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatient(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg13), arg14, arg15, arg16);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatient(arg0, arg1, arg2, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg8), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg9), arg10, arg11, arg12, to_candid_opt_n31(this._uploadFile, this._downloadFile, arg13), arg14, arg15, arg16);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updatePostureStatus(arg0: bigint, arg1: string): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePostureStatus(arg0, arg1);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePostureStatus(arg0, arg1);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSalineLevel(arg0: bigint, arg1: bigint): Promise<Patient> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSalineLevel(arg0, arg1);
                return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSalineLevel(arg0, arg1);
            return from_candid_Patient_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateUser(arg0: bigint, arg1: string, arg2: string, arg3: Role, arg4: bigint | null, arg5: string | null, arg6: string | null): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
                return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, arg1, arg2, to_candid_Role_n14(this._uploadFile, this._downloadFile, arg3), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg6));
            return from_candid_User_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Alert_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Alert): Alert {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Assignment_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Assignment): Assignment {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Patient_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Patient): Patient {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_User_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    age: bigint;
    caregiverId: [] | [bigint];
    name: string;
    lastGestureAlert: [] | [_Time];
    photoUrl: [] | [string];
    familyMemberIds: Array<bigint>;
    bedNumber: string;
    emergencyContacts: Array<string>;
    isActive: boolean;
    uniqueCode: string;
    salineLevel: bigint;
    hospitalId: bigint;
    postureStatus: string;
    medicalHistory: string;
    nurseId: [] | [bigint];
    bloodGroup: string;
}): {
    id: bigint;
    age: bigint;
    caregiverId?: bigint;
    name: string;
    lastGestureAlert?: Time;
    photoUrl?: string;
    familyMemberIds: Array<bigint>;
    bedNumber: string;
    emergencyContacts: Array<string>;
    isActive: boolean;
    uniqueCode: string;
    salineLevel: bigint;
    hospitalId: bigint;
    postureStatus: string;
    medicalHistory: string;
    nurseId?: bigint;
    bloodGroup: string;
} {
    return {
        id: value.id,
        age: value.age,
        caregiverId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.caregiverId)),
        name: value.name,
        lastGestureAlert: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.lastGestureAlert)),
        photoUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.photoUrl)),
        familyMemberIds: value.familyMemberIds,
        bedNumber: value.bedNumber,
        emergencyContacts: value.emergencyContacts,
        isActive: value.isActive,
        uniqueCode: value.uniqueCode,
        salineLevel: value.salineLevel,
        hospitalId: value.hospitalId,
        postureStatus: value.postureStatus,
        medicalHistory: value.medicalHistory,
        nurseId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.nurseId)),
        bloodGroup: value.bloodGroup
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    role: _Role;
    email: string;
    hospitalId: [] | [bigint];
    profilePhotoUrl: [] | [string];
    phone: [] | [string];
}): {
    id: bigint;
    name: string;
    role: Role;
    email: string;
    hospitalId?: bigint;
    profilePhotoUrl?: string;
    phone?: string;
} {
    return {
        id: value.id,
        name: value.name,
        role: from_candid_Role_n18(_uploadFile, _downloadFile, value.role),
        email: value.email,
        hospitalId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.hospitalId)),
        profilePhotoUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.profilePhotoUrl)),
        phone: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: string;
    caregiverId: [] | [bigint];
    patientId: bigint;
    createdAt: _Time;
    nurseId: bigint;
}): {
    id: bigint;
    status: string;
    caregiverId?: bigint;
    patientId: bigint;
    createdAt: Time;
    nurseId: bigint;
} {
    return {
        id: value.id,
        status: value.status,
        caregiverId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.caregiverId)),
        patientId: value.patientId,
        createdAt: value.createdAt,
        nurseId: value.nurseId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: bigint;
    name: string;
    role: _Role;
    email: string;
    hospitalId: [] | [bigint];
    profilePhotoUrl: [] | [string];
    phone: [] | [string];
}): {
    userId: bigint;
    name: string;
    role: Role;
    email: string;
    hospitalId?: bigint;
    profilePhotoUrl?: string;
    phone?: string;
} {
    return {
        userId: value.userId,
        name: value.name,
        role: from_candid_Role_n18(_uploadFile, _downloadFile, value.role),
        email: value.email,
        hospitalId: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.hospitalId)),
        profilePhotoUrl: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.profilePhotoUrl)),
        phone: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    resolved: boolean;
    alertType: string;
    patientId: bigint;
    notes: [] | [string];
    timestamp: _Time;
    severity: string;
    resolvedBy: [] | [bigint];
}): {
    id: bigint;
    resolved: boolean;
    alertType: string;
    patientId: bigint;
    notes?: string;
    timestamp: Time;
    severity: string;
    resolvedBy?: bigint;
} {
    return {
        id: value.id,
        resolved: value.resolved,
        alertType: value.alertType,
        patientId: value.patientId,
        notes: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.notes)),
        timestamp: value.timestamp,
        severity: value.severity,
        resolvedBy: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.resolvedBy))
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    patient: null;
} | {
    admin: null;
} | {
    familyMember: null;
} | {
    nurse: null;
} | {
    caregiver: null;
}): Role {
    return "patient" in value ? Role.patient : "admin" in value ? Role.admin : "familyMember" in value ? Role.familyMember : "nurse" in value ? Role.nurse : "caregiver" in value ? Role.caregiver : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Alert>): Array<Alert> {
    return value.map((x)=>from_candid_Alert_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Assignment>): Array<Assignment> {
    return value.map((x)=>from_candid_Assignment_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_User>): Array<User> {
    return value.map((x)=>from_candid_User_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Patient>): Array<Patient> {
    return value.map((x)=>from_candid_Patient_n11(_uploadFile, _downloadFile, x));
}
function to_candid_Role_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Time | null): [] | [_Time] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userId: bigint;
    name: string;
    role: Role;
    email: string;
    hospitalId?: bigint;
    profilePhotoUrl?: string;
    phone?: string;
}): {
    userId: bigint;
    name: string;
    role: _Role;
    email: string;
    hospitalId: [] | [bigint];
    profilePhotoUrl: [] | [string];
    phone: [] | [string];
} {
    return {
        userId: value.userId,
        name: value.name,
        role: to_candid_Role_n14(_uploadFile, _downloadFile, value.role),
        email: value.email,
        hospitalId: value.hospitalId ? candid_some(value.hospitalId) : candid_none(),
        profilePhotoUrl: value.profilePhotoUrl ? candid_some(value.profilePhotoUrl) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    patient: null;
} | {
    admin: null;
} | {
    familyMember: null;
} | {
    nurse: null;
} | {
    caregiver: null;
} {
    return value == Role.patient ? {
        patient: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.familyMember ? {
        familyMember: null
    } : value == Role.nurse ? {
        nurse: null
    } : value == Role.caregiver ? {
        caregiver: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
